database:
 secret: ${PASS_DB_SECRET:secret}
 set: mongodb://mongo:kCAGjooRJZMdUrLwkYyoOsvlimBDXjsc@roundhouse.proxy.rlwy.net:23283,monorail.proxy.rlwy.net:33179,roundhouse.proxy.rlwy.net:41753/?replicaSet=rs0&authSource=admin
grpc:
 host: ${PASS_GRPC_HOST:localhost}
 port: ${PASS_GRPC_PORT:50051}
 cert_path: ${PASS_SERVER_CERT_PATH:../creds/server/server-cert.pem}
 key_path: ${PASS_SERVER_KEY_PATH:../creds/server/server-key.pem}
 ca_cert_path: ${PASS_ROOT_CERT_PATH:../creds/ca-cert.pem}
auth:
 secret: ${PASS_GRPC_SECRET:your_grpc_secret}