name: Go

on:
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]

jobs:
 build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Build Client
      run: go build -v -o client ./cmd/client/
    - name: Build Server
      run: go build -v -o server ./cmd/server/
    - name: Test
      run: go test -cover ./internal/...
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-build
        path: |
          ./client
          ./server